# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('series', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'characters',
                'managed': False,
            },
        ),
    ]
